dataset:
  name: 'thumos'
  num_classes: 20
  split: 50
  training:
    video_info_path: "./data/thumos_annotations/video_info_new.csv"
    video_anno_path: "./data/thumos_annotations/thumos_anno_action.json"    
  testing:
    video_info_path: "./data/thumos_annotations/video_info_new.csv"
    video_anno_path: "./data/thumos_annotations/thumos_anno_action.json"


training:
  feature_path: 
  video_path: 
  from_features: True
  baseline: True
  oracle: False
  extract: False